
# The task is a string displayed on top of the GUI
# This defines the fontsize and the space between
# the task and the rating interface in pixel
task_fontsize: 16
task_spacing: 24

# This
description_font_size: 12
label_fontsize: 12


autoplay_reference: True
autoplay_delay: .5

window_size: (1100, 550)
verbose: True

fontcolor: "#e8eaed"
window_background_color: "#2b2b2b"
rating_area_background_color: "#f6f7f9"
edge_color: "#d7dbe0"

button_color_initial: "#ffffff"
button_color_clicked: "#d9dde3"
button_color_active: "#a5d6a7"

button_number: 4
button_size: 40
button_fontsize: 16
button_spacing: 8